name: Deploy to King's Landing

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to King's Landing
        uses: boxshopio/deploy-to-kingslanding@v2
        with:
          project: example-site
          directory: .
          deploy-key: ${{ secrets.KL_DEPLOY_KEY }}
