name: Deploy to King's Landing

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KL_DEPLOY_KEY: ${{ secrets.KL_DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to King's Landing
        if: env.KL_DEPLOY_KEY != ''
        uses: boxshopio/deploy-to-kingslanding@v2
        with:
          project: demo
          directory: .
          deploy-key: ${{ env.KL_DEPLOY_KEY }}
