name: Deploy to King's Landing

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to King's Landing
        if: ${{ secrets.KL_DEPLOY_KEY != '' }}
        uses: boxshopio/deploy-to-kingslanding@v1
        with:
          project: demo
          directory: .
          deploy-key: ${{ secrets.KL_DEPLOY_KEY }}
